import {
  SettingOutlined,
  SolutionOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { Breadcrumb, Layout, Menu } from "antd";
import Link from "next/link";
import Head from "next/head";
import { deleteCookie } from "cookies-next";
import { useRouter } from "next/router";
import Cookie from "js-cookie";

const { Header, Content, Footer } = Layout;

const LayoutApp = ({ children }: any) => {
  const router = useRouter();
  const handleLogout = () => {
    Cookie.remove("token");
    router.push("/auth/login");
  };
  return (
    <Layout className="layout">
      <Head>
        <title>User management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Header>
          <div className="demo-logo" />
          <Menu
            theme="dark"
            mode="horizontal"
            defaultSelectedKeys={["1"]}
            items={[
              {
                key: "1",
                icon: <UserOutlined />,
                label: <Link href={"/"}>User Management</Link>,
              },
              {
                key: "2",
                icon: <SolutionOutlined />,
                label: <Link href={"/roles"}>Role Management</Link>,
              },
              {
                key: "3",
                icon: <SettingOutlined />,
                label: "Options",
                children: [
                  {
                    label: "Logout",
                    key: "logout",
                    onClick: () => {
                      handleLogout();
                    },
                  },
                ],
              },
            ]}
          />
        </Header>
        <Content style={{ padding: "0 50px" }}>
          <Breadcrumb style={{ margin: "16px 0" }}></Breadcrumb>
          {children}
        </Content>
        <Footer style={{ textAlign: "center" }}></Footer>
      </div>
    </Layout>
  );
};

export default LayoutApp;
